name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - 'backend/**'

stages:
  - update_submodules

update_submodules_job:
  stage: update_submodules
  script:
    - git submodule sync --recursive
    - git submodule update --init --recursive --remote
    - git add .
    - git commit -m "Updated submodules"
    - git push origin main
