# CI for submodules

name: CI

stages:
  - update_submodules

update_submodules_job:
  stage: update_submodules
  only:
    refs:
      - master
    changes:
      - frontend/**/*
      - backend/**/*

  script:
    - git submodules sync --recursive
    - git submodules update --init --recursive --remote
    - git commit -am "Updated submodules"
    - git push origin main
