name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  update_submodules_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote
          git add .
          git commit -m "Update submodules"
          git push origin main
